// Test data for development - can be replaced with actual API calls
export const testVacancies = [
  {
    id: 1,
    company_id: 1,
    title: 'Senior React Developer',
    description: 'We are looking for an experienced React developer to join our frontend team. You will work on building scalable web applications with modern technologies.',
    salary_min: 120000,
    salary_max: 160000,
    currency: 'USD',
    employment_type: 'full_time',
    experience_level: 'senior',
    location: 'San Francisco, CA',
    industry: 'Technology',
    skills_required: ['React', 'TypeScript', 'Testing', 'Performance'],
    applications_count: 12,
    views_count: 145,
    created_at: '2024-02-10T00:00:00Z',
    is_active: true,
    company_name: 'TechCorp Solutions',
    company_logo: '💻',
  },
  {
    id: 2,
    company_id: 1,
    title: 'Backend Engineer - Node.js',
    description: 'Build and maintain our API backend using Node.js and PostgreSQL. You will be responsible for system design, performance optimization, and code quality.',
    salary_min: 100000,
    salary_max: 140000,
    currency: 'USD',
    employment_type: 'full_time',
    experience_level: 'mid',
    location: 'San Francisco, CA',
    industry: 'Technology',
    skills_required: ['Node.js', 'PostgreSQL', 'API Design', 'System Design'],
    applications_count: 8,
    views_count: 98,
    created_at: '2024-02-08T00:00:00Z',
    is_active: true,
    company_name: 'TechCorp Solutions',
    company_logo: '💻',
  },
  {
    id: 3,
    company_id: 2,
    title: 'Cloud Infrastructure Engineer',
    description: 'Looking for a DevOps engineer to design and manage our cloud infrastructure on AWS. Experience with Kubernetes, Terraform, and CI/CD pipelines required.',
    salary_min: 110000,
    salary_max: 150000,
    currency: 'USD',
    employment_type: 'full_time',
    experience_level: 'mid',
    location: 'New York, NY',
    industry: 'Cloud Computing',
    skills_required: ['Kubernetes', 'AWS', 'Terraform', 'Docker'],
    applications_count: 5,
    views_count: 67,
    created_at: '2024-02-07T00:00:00Z',
    is_active: true,
    company_name: 'CloudBase Inc',
    company_logo: '☁️',
  },
  {
    id: 4,
    company_id: 2,
    title: 'Solutions Architect',
    description: 'Join our team as a Solutions Architect to design cloud solutions for enterprise clients. You will work with AWS, Azure, and GCP.',
    salary_min: 130000,
    salary_max: 170000,
    currency: 'USD',
    employment_type: 'full_time',
    experience_level: 'senior',
    location: 'New York, NY',
    industry: 'Cloud Computing',
    skills_required: ['Cloud Architecture', 'AWS', 'System Design'],
    applications_count: 3,
    views_count: 42,
    created_at: '2024-02-06T00:00:00Z',
    is_active: true,
    company_name: 'CloudBase Inc',
    company_logo: '☁️',
  },
  {
    id: 5,
    company_id: 3,
    title: 'Machine Learning Engineer',
    description: 'Develop ML models and algorithms for our data platform. Strong background in Python, TensorFlow, and statistical analysis required.',
    salary_min: 115000,
    salary_max: 155000,
    currency: 'USD',
    employment_type: 'full_time',
    experience_level: 'mid',
    location: 'Boston, MA',
    industry: 'AI/ML',
    skills_required: ['Machine Learning', 'Python', 'TensorFlow'],
    applications_count: 7,
    views_count: 89,
    created_at: '2024-02-05T00:00:00Z',
    is_active: true,
    company_name: 'DataVision Analytics',
    company_logo: '📊',
  },
  {
    id: 6,
    company_id: 3,
    title: 'Data Engineer',
    description: 'Build scalable data pipelines and data warehouses. Experience with Apache Spark, Airflow, and data modeling required.',
    salary_min: 105000,
    salary_max: 145000,
    currency: 'USD',
    employment_type: 'full_time',
    experience_level: 'mid',
    location: 'Boston, MA',
    industry: 'AI/ML',
    skills_required: ['Apache Spark', 'SQL', 'Data Warehousing'],
    applications_count: 4,
    views_count: 56,
    created_at: '2024-02-04T00:00:00Z',
    is_active: true,
    company_name: 'DataVision Analytics',
    company_logo: '📊',
  },
  {
    id: 7,
    company_id: 4,
    title: 'Security Engineer',
    description: 'Protect our systems and infrastructure from security threats. You will work on security architecture, penetration testing, and vulnerability management.',
    salary_min: 120000,
    salary_max: 160000,
    currency: 'USD',
    employment_type: 'full_time',
    experience_level: 'senior',
    location: 'Austin, TX',
    industry: 'Cybersecurity',
    skills_required: ['Security Architecture', 'Penetration Testing', 'System Security'],
    applications_count: 2,
    views_count: 38,
    created_at: '2024-02-03T00:00:00Z',
    is_active: true,
    company_name: 'SecureNet Systems',
    company_logo: '🔐',
  },
  {
    id: 8,
    company_id: 4,
    title: 'Junior Security Analyst',
    description: 'Start your cybersecurity career with us. You will monitor systems, analyze logs, and help respond to security incidents.',
    salary_min: 60000,
    salary_max: 85000,
    currency: 'USD',
    employment_type: 'full_time',
    experience_level: 'entry',
    location: 'Austin, TX',
    industry: 'Cybersecurity',
    skills_required: ['Network Security', 'Log Analysis', 'Security Monitoring'],
    applications_count: 15,
    views_count: 125,
    created_at: '2024-02-02T00:00:00Z',
    is_active: true,
    company_name: 'SecureNet Systems',
    company_logo: '🔐',
  },
  {
    id: 9,
    company_id: 5,
    title: 'Senior UI/UX Designer',
    description: 'Lead design for our web and mobile applications. You will work on user research, wireframing, prototyping, and design systems.',
    salary_min: 95000,
    salary_max: 130000,
    currency: 'USD',
    employment_type: 'full_time',
    experience_level: 'senior',
    location: 'Los Angeles, CA',
    industry: 'Design',
    skills_required: ['Figma', 'User Research', 'Design Systems'],
    applications_count: 6,
    views_count: 72,
    created_at: '2024-02-01T00:00:00Z',
    is_active: true,
    company_name: 'DesignStudio Creative',
    company_logo: '🎨',
  },
  {
    id: 10,
    company_id: 5,
    title: 'Product Designer',
    description: 'Join our product team to design delightful user experiences. Collaborate with product managers and engineers to create innovative solutions.',
    salary_min: 85000,
    salary_max: 115000,
    currency: 'USD',
    employment_type: 'full_time',
    experience_level: 'mid',
    location: 'Los Angeles, CA',
    industry: 'Design',
    skills_required: ['Product Design', 'Figma', 'Prototyping'],
    applications_count: 9,
    views_count: 103,
    created_at: '2024-01-31T00:00:00Z',
    is_active: true,
    company_name: 'DesignStudio Creative',
    company_logo: '🎨',
  },
]
